[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "needle"
version = "0.1.1"
dependencies = [
  "heap @ git+https://github.com/benjiec/tangle-heap.git@7f3d8c2",
  "tangle @ git+https://github.com/benjiec/tangle.git@1f7c7d9",
  "biopython>=1.81",
  "gffutils>=0.14",
  "bcbio-gff>=0.6.9",
  "pyahocorasick>=2.3.0",
  "networkx>=3.6.1"
]
description = "Protein Detection from HMM Profiles"
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
]

[tool.setuptools.packages.find]
where = ["."]
