#!/bin/bash

# arguments, in order:
#   - module ID (i.e. mNNN)
#   - genome accession

mkdir -p data/$1_results/detected

if [ -f "data/$1_results/detected/$1_$2.tsv" ]; then
  echo "Found existing detection results for $2"
else
  echo "Searching $2"
  PYTHONPATH=. python3 scripts/detect/hmmsearch-genome.py --cpu 2 data/$1_ko.hmm $2 data/$1_results/detected/$1_$2.tsv
fi

echo "Collating search results for $2"
PYTHONPATH=. python3 scripts/detect/export-protein-results.py data/$1_results/detected/$1_$2.tsv $2 data/$1_ko.hmm data/$1_results
